## Simple SVM

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.metrics import accuracy_score
import pandas as pd

C:\Users\Lab\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
from ucimlrepo import fetch_ucirepo 
car_evaluation = fetch_ucirepo(id=19) 

X = car_evaluation.data.features 
y = car_evaluation.data.targets

In [28]:
car_evaluation.variables

,name,role,type,demographic,description,units,missing_values
0,buying,Feature,Categorical,None,buying price,None,no
1,maint,Feature,Categorical,None,price of the maintenance,None,no
2,doors,Feature,Categorical,None,number of doors,None,no
3,persons,Feature,Categorical,None,capacity in terms of persons to carry,None,no
4,lug_boot,Feature,Categorical,None,the size of luggage boot,None,no
5,safety,Feature,Categorical,None,estimated safety of the car,None,no
6,class,Target,Categorical,None,"evaulation level (unacceptable, acceptable, go...",None,no

In [29]:
car_evaluation.variables['description'][6]

'evaulation level (unacceptable, acceptable, good, very good)'

In [3]:
df = pd.concat([X,y], axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder = LabelEncoder()

In [7]:
for i in X.columns:
    if X[i].dtype=='object':
        X.loc[:,i] = encoder.fit_transform(X[i])
    print(X[i].value_counts())

buying
3    432
0    432
2    432
1    432
Name: count, dtype: int64
maint
3    432
0    432
2    432
1    432
Name: count, dtype: int64
doors
0    432
1    432
2    432
3    432
Name: count, dtype: int64
persons
0    576
1    576
2    576
Name: count, dtype: int64
lug_boot
2    576
1    576
0    576
Name: count, dtype: int64
safety
1    576
2    576
0    576
Name: count, dtype: int64

In [8]:
X = pd.get_dummies(X, columns=X.columns, drop_first=True)

In [9]:
X

,buying_1,buying_2,buying_3,maint_1,maint_2,maint_3,doors_1,doors_2,doors_3,persons_1,persons_2,lug_boot_1,lug_boot_2,safety_1,safety_2
0,False,False,True,False,False,True,False,False,False,False,False,False,True,True,False
1,False,False,True,False,False,True,False,False,False,False,False,False,True,False,True
2,False,False,True,False,False,True,False,False,False,False,False,False,True,False,False
3,False,False,True,False,False,True,False,False,False,False,False,True,False,True,False
4,False,False,True,False,False,True,False,False,False,False,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,True,False,False,True,False,False,False,False,True,False,True,True,False,False,True
1724,True,False,False,True,False,False,False,False,True,False,True,True,False,False,False
1725,True,False,False,True,False,False,False,False,True,False,True,False,False,True,False
1726,True,False,False,True,False,False,False,False,True,False,True,False,False,False,True
1727,True,False,False,True,False,False,False,False,True,False,True,False,False,False,False

In [10]:
X = X.astype(int)
X

,buying_1,buying_2,buying_3,maint_1,maint_2,maint_3,doors_1,doors_2,doors_3,persons_1,persons_2,lug_boot_1,lug_boot_2,safety_1,safety_2
0,0,0,1,0,0,1,0,0,0,0,0,0,1,1,0
1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,1
2,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0
3,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0
4,0,0,1,0,0,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,1,0,0,1,0,0,0,0,1,0,1,1,0,0,1
1724,1,0,0,1,0,0,0,0,1,0,1,1,0,0,0
1725,1,0,0,1,0,0,0,0,1,0,1,0,0,1,0
1726,1,0,0,1,0,0,0,0,1,0,1,0,0,0,1
1727,1,0,0,1,0,0,0,0,1,0,1,0,0,0,0

In [11]:
y=df.iloc[:,-1]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
svm = SVC()
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_svm)
print("Accuracy:", accuracy)

Accuracy: 0.9421965317919075

In [14]:
lin_svm = SVC(kernel='linear')
lin_svm.fit(X_train, y_train)
y_pred_lin = lin_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lin)
print("Accuracy:", accuracy)

Accuracy: 0.9190751445086706

In [15]:
rbf_svm = SVC(kernel='rbf')
rbf_svm.fit(X_train, y_train)
y_pred_rbf = rbf_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_rbf)
print("Accuracy:", accuracy)

Accuracy: 0.9421965317919075

In [16]:
soft_svm = SVC(kernel='linear', C=5, gamma='scale')
soft_svm.fit(X_train, y_train)
y_pred_soft = soft_svm.predict(X_test)
y_pred_soft_train = soft_svm.predict(X_train)
accuracy_on_test = accuracy_score(y_test, y_pred_soft)
accuracy_on_train = accuracy_score(y_train, y_pred_soft_train)
print("Accuracy on Test data:", accuracy_on_test)
print("Accuracy on Train data:", accuracy_on_train)

Accuracy on Test data: 0.9267822736030829
Accuracy on Train data: 0.9503722084367245

In [17]:
poly_svm = SVC(kernel='poly', degree=3)
poly_svm.fit(X_train, y_train)
y_pred_poly = poly_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_poly)
print("Accuracy:", accuracy)

Accuracy: 0.953757225433526

In [18]:
nu_svm = NuSVC(nu=0.09, kernel='rbf')
nu_svm.fit(X_train, y_train)
y_pred_nu = nu_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_nu)
print("Accuracy:", accuracy)

Accuracy: 0.9710982658959537

In [19]:
models = [svm, lin_svm, rbf_svm, soft_svm, poly_svm, nu_svm]

In [20]:
for i in models:
    print(i.n_support_)

[244  50 282  41]
[177  43 134  35]
[244  50 282  41]
[146  43 111  33]
[176  44 224  39]
[209  48 224  41]

In [21]:
for i in models:
    print("indices of sv for " , i)
    print(i.support_)

indices of sv for  SVC()
[   2   10   12   15   17   29   32   34   35   42   57   62   66   69
   71   79   80   82   94   98   99  101  132  133  139  145  146  156
  157  161  167  169  172  176  179  181  185  187  204  209  218  228
  232  250  264  268  275  281  283  286  287  295  298  301  305  316
  326  333  338  341  350  351  353  354  360  367  383  384  387  393
  399  406  412  416  422  430  441  460  462  475  476  479  482  487
  490  492  493  496  498  500  504  505  506  510  513  518  524  530
  535  541  542  545  548  555  561  563  567  577  583  586  588  601
  603  604  607  618  625  628  630  632  634  638  645  659  674  682
  689  695  696  699  700  701  703  705  707  716  717  720  727  729
  741  752  757  761  763  765  769  772  778  788  796  800  804  808
  809  818  822  823  828  831  832  836  846  848  861  865  866  873
  876  884  890  892  893  894  895  897  910  918  925  931  936  942
  948  949  951  953  955  962  964  969  974  975  978  980  983  995
 1000 1009 1011 1016 1025 1030 1041 1043 1044 1049 1050 1070 1071 1074
 1077 1081 1082 1083 1084 1087 1088 1090 1094 1102 1103 1105 1106 1107
 1113 1114 1122 1123 1125 1126 1128 1134 1135 1137 1139 1144 1153 1155
 1162 1176 1183 1193 1206 1208   40   55   77  106  112  125  126  135
  143  171  276  300  318  328  347  352  396  445  461  483  499  517
  594  600  649  669  711  791  810  816  870  880  882  913  944  947
  989  994  997 1006 1020 1042 1054 1117 1136 1156 1158 1189 1191 1205
    3    9   11   18   21   39   41   44   46   54   56   58   59   60
   63   65   68   73   74   75   81   83   87   90   92   93   95   96
  103  110  113  117  118  121  130  131  140  148  151  154  155  158
  160  164  174  175  180  184  188  193  194  198  199  205  206  210
  212  213  222  223  226  241  242  244  249  255  257  270  271  272
  274  277  278  282  291  292  296  297  304  310  313  319  320  323
  325  327  331  332  342  344  345  349  355  356  359  365  369  374
  388  394  397  403  405  407  408  411  413  414  415  419  420  423
  425  434  437  438  443  449  450  452  453  455  466  468  472  474
  480  485  486  489  508  512  515  519  522  526  527  532  533  537
  550  554  556  558  568  571  576  578  580  587  602  605  606  609
  613  615  619  624  635  636  639  646  656  662  676  678  679  680
  685  709  710  718  721  722  731  734  736  738  745  748  751  758
  777  780  781  783  789  794  797  798  799  802  803  826  834  838
  839  840  841  851  852  854  856  859  862  872  874  877  889  891
  896  898  900  902  905  906  907  914  921  923  924  930  939  941
  943  945  954  965  966  967  968  971  990  992  998  999 1005 1010
 1014 1015 1017 1024 1028 1029 1031 1035 1038 1040 1048 1052 1053 1058
 1060 1061 1065 1067 1072 1073 1089 1098 1101 1104 1110 1112 1116 1121
 1130 1133 1142 1143 1159 1160 1161 1163 1166 1171 1172 1180 1187 1194
 1196 1203    0  124  168  220  303  373  389  409  417  427  473  520
  569  616  623  637  648  654  655  693  694  715  774  790  833  857
  899  929  972  986  993 1018 1037 1045 1055 1111 1154 1167 1178 1198
 1204]
indices of sv for  SVC(kernel='linear')
[   2   10   17   29   32   34   42   48   62   71   79   80   82   98
   99  101  132  133  139  156  157  165  167  169  172  176  179  181
  185  187  209  250  261  264  268  275  281  286  287  298  301  305
  333  350  354  360  367  383  384  393  399  406  412  416  422  430
  451  460  462  475  476  479  482  490  492  493  496  505  506  518
  530  541  545  548  555  561  563  567  583  586  598  601  603  604
  607  618  625  628  630  632  634  638  674  696  701  716  717  720
  727  729  752  755  757  761  763  772  778  788  796  808  809  818
  822  828  832  836  848  861  865  873  876  890  892  893  894  897
  910  925  931  936  948  949  953  955  957  962  964  969  975  978
  980  995 1000 1009 1025 1030 1041 1043 1044 1050 1070 1077 1081 1082
 1083 1084 1087 1090 1102 1103 1105 1106 1107 1114 1123 1125 1126 1128
 1137 1139 1144 1153 1155 1162 1183 1193 1208   40   55   77  112  135
  143  171  276  300  318  328  347  352  396  445  461  483  499  517
  594  600  649  669  791  810  816  870  882  913  944  947  989  994
  997 1006 1020 1042 1054 1117 1156 1158 1189 1205    3   18   21   39
   41   44   56   59   60   63   65   67   68   83   90   95  107  130
  131  154  160  175  178  180  184  194  198  205  226  241  244  249
  271  272  277  278  291  292  302  313  342  344  345  349  359  369
  374  405  414  420  423  429  434  438  440  443  449  450  468  480
  494  521  522  537  550  554  560  568  576  592  624  636  646  662
  718  731  734  736  738  748  770  789  794  797  826  839  851  856
  859  872  874  877  889  891  896  898  900  902  908  909  924  939
  941  965  966  990  999 1024 1029 1031 1035 1039 1048 1052 1053 1058
 1064 1067 1072 1073 1104 1110 1116 1130 1132 1142 1143 1160 1161 1172
 1180 1187 1194 1196    0  124  168  220  303  373  389  409  417  473
  520  569  616  623  637  648  655  693  715  790  833  929  972  986
  993 1018 1037 1045 1055 1111 1154 1167 1178 1198 1204]
indices of sv for  SVC()
[   2   10   12   15   17   29   32   34   35   42   57   62   66   69
   71   79   80   82   94   98   99  101  132  133  139  145  146  156
  157  161  167  169  172  176  179  181  185  187  204  209  218  228
  232  250  264  268  275  281  283  286  287  295  298  301  305  316
  326  333  338  341  350  351  353  354  360  367  383  384  387  393
  399  406  412  416  422  430  441  460  462  475  476  479  482  487
  490  492  493  496  498  500  504  505  506  510  513  518  524  530
  535  541  542  545  548  555  561  563  567  577  583  586  588  601
  603  604  607  618  625  628  630  632  634  638  645  659  674  682
  689  695  696  699  700  701  703  705  707  716  717  720  727  729
  741  752  757  761  763  765  769  772  778  788  796  800  804  808
  809  818  822  823  828  831  832  836  846  848  861  865  866  873
  876  884  890  892  893  894  895  897  910  918  925  931  936  942
  948  949  951  953  955  962  964  969  974  975  978  980  983  995
 1000 1009 1011 1016 1025 1030 1041 1043 1044 1049 1050 1070 1071 1074
 1077 1081 1082 1083 1084 1087 1088 1090 1094 1102 1103 1105 1106 1107
 1113 1114 1122 1123 1125 1126 1128 1134 1135 1137 1139 1144 1153 1155
 1162 1176 1183 1193 1206 1208   40   55   77  106  112  125  126  135
  143  171  276  300  318  328  347  352  396  445  461  483  499  517
  594  600  649  669  711  791  810  816  870  880  882  913  944  947
  989  994  997 1006 1020 1042 1054 1117 1136 1156 1158 1189 1191 1205
    3    9   11   18   21   39   41   44   46   54   56   58   59   60
   63   65   68   73   74   75   81   83   87   90   92   93   95   96
  103  110  113  117  118  121  130  131  140  148  151  154  155  158
  160  164  174  175  180  184  188  193  194  198  199  205  206  210
  212  213  222  223  226  241  242  244  249  255  257  270  271  272
  274  277  278  282  291  292  296  297  304  310  313  319  320  323
  325  327  331  332  342  344  345  349  355  356  359  365  369  374
  388  394  397  403  405  407  408  411  413  414  415  419  420  423
  425  434  437  438  443  449  450  452  453  455  466  468  472  474
  480  485  486  489  508  512  515  519  522  526  527  532  533  537
  550  554  556  558  568  571  576  578  580  587  602  605  606  609
  613  615  619  624  635  636  639  646  656  662  676  678  679  680
  685  709  710  718  721  722  731  734  736  738  745  748  751  758
  777  780  781  783  789  794  797  798  799  802  803  826  834  838
  839  840  841  851  852  854  856  859  862  872  874  877  889  891
  896  898  900  902  905  906  907  914  921  923  924  930  939  941
  943  945  954  965  966  967  968  971  990  992  998  999 1005 1010
 1014 1015 1017 1024 1028 1029 1031 1035 1038 1040 1048 1052 1053 1058
 1060 1061 1065 1067 1072 1073 1089 1098 1101 1104 1110 1112 1116 1121
 1130 1133 1142 1143 1159 1160 1161 1163 1166 1171 1172 1180 1187 1194
 1196 1203    0  124  168  220  303  373  389  409  417  427  473  520
  569  616  623  637  648  654  655  693  694  715  774  790  833  857
  899  929  972  986  993 1018 1037 1045 1055 1111 1154 1167 1178 1198
 1204]
indices of sv for  SVC(C=5, kernel='linear')
[   2   10   29   32   34   42   62   79   80   82   98  101  132  133
  139  156  165  167  169  176  179  181  185  187  209  250  261  268
  275  281  286  287  298  301  305  333  350  360  367  383  384  393
  406  416  422  430  451  460  462  475  476  479  482  490  496  506
  518  530  541  548  555  563  567  586  601  604  607  618  625  628
  634  670  674  696  701  716  720  727  729  752  761  763  772  778
  788  804  808  809  818  822  828  836  848  865  866  873  890  892
  893  897  910  925  931  936  948  949  951  953  955  964  975  978
  980  983  995 1000 1009 1016 1025 1030 1041 1044 1050 1062 1070 1077
 1081 1082 1083 1087 1090 1102 1103 1106 1107 1123 1126 1137 1139 1144
 1153 1155 1162 1183 1193 1206   40   55   77  106  112  126  135  143
  171  276  300  318  328  347  352  396  445  461  499  517  594  649
  669  711  791  810  816  870  882  913  944  947  989  994  997 1006
 1042 1054 1117 1156 1158 1189 1205    3   39   41   56   59   60   63
   65   67   68   90  107  130  131  154  160  175  180  184  194  198
  205  226  244  249  255  271  277  278  291  313  342  344  349  359
  369  374  378  405  414  420  423  429  434  438  440  443  449  480
  494  508  521  522  537  550  554  568  571  576  624  636  646  662
  718  731  734  736  738  748  770  789  794  826  839  851  856  872
  874  877  889  896  898  900  902  908  924  939  941  965  966  999
 1024 1035 1039 1048 1052 1064 1073 1098 1104 1116 1130 1142 1143 1159
 1161 1172 1180 1187 1194 1196    0  168  220  373  389  409  417  473
  569  616  637  648  654  693  694  715  790  833  857  929  972  986
  993 1018 1037 1045 1055 1111 1154 1167 1178 1198 1204]
indices of sv for  SVC(kernel='poly')
[   2   10   12   15   17   34   42   48   57   62   69   82   94   98
  132  133  139  156  157  161  165  167  169  176  179  181  187  209
  232  250  261  264  268  275  283  286  298  301  305  316  326  338
  341  350  351  354  360  367  383  384  393  399  406  412  416  422
  441  451  460  475  479  482  487  490  492  493  496  498  500  504
  505  506  513  518  530  542  548  555  561  563  577  583  586  601
  603  618  625  628  630  634  658  659  670  674  696  700  701  703
  705  707  716  717  720  727  729  741  752  757  761  765  772  778
  796  800  804  809  818  823  828  832  848  865  866  876  884  890
  895  897  925  931  948  951  955  969  974  975  978  980  983  995
 1000 1009 1011 1016 1025 1030 1041 1044 1071 1077 1081 1082 1083 1084
 1087 1088 1090 1094 1102 1103 1105 1107 1114 1122 1123 1126 1128 1134
 1135 1139 1144 1153 1155 1193 1206 1208   40   55   77  106  112  126
  135  143  171  276  300  318  328  352  396  445  461  483  499  517
  594  600  649  669  711  791  816  870  882  913  944  947  994  997
 1006 1020 1054 1117 1136 1156 1158 1189 1191 1205    3    8    9   11
   18   21   39   41   46   47   56   58   59   60   61   63   65   67
   68   73   81   83   90   92   93  103  113  119  130  131  140  148
  150  154  158  160  164  174  175  180  188  190  193  202  203  205
  206  223  226  234  241  242  244  245  249  251  270  271  272  274
  278  282  289  297  307  313  320  327  342  344  349  359  365  369
  372  374  379  388  390  397  403  407  408  411  413  414  415  420
  423  433  434  437  438  443  450  455  459  466  474  485  486  503
  508  512  522  528  532  533  534  537  544  550  554  556  557  568
  571  576  587  591  602  605  609  615  624  635  636  639  646  653
  656  662  685  709  710  731  736  745  748  750  758  759  777  779
  780  794  795  797  798  799  801  827  835  838  839  840  841  851
  854  856  862  874  877  879  889  891  896  898  900  902  903  906
  914  923  924  927  932  941  943  954  965  966  968  971  988  990
  996  998  999 1003 1010 1024 1028 1029 1031 1035 1038 1040 1048 1056
 1058 1063 1065 1072 1098 1101 1104 1110 1112 1116 1121 1127 1130 1143
 1157 1159 1160 1161 1171 1172 1187 1194 1196 1203    0  124  168  220
  303  373  389  409  417  427  473  520  569  616  623  637  648  654
  655  693  694  715  790  833  899  929  972  986  993 1018 1037 1045
 1055 1111 1154 1167 1178 1198 1204]
indices of sv for  NuSVC(nu=0.09)
[   2   10   12   15   17   29   32   34   35   42   57   62   69   71
   79   80   98   99  101  123  132  133  139  146  156  157  161  167
  169  176  179  181  185  187  204  209  218  228  232  250  268  275
  281  286  287  298  301  305  316  326  333  338  341  350  354  360
  367  381  383  387  393  399  406  416  422  430  441  460  462  475
  476  479  482  487  490  492  493  498  500  504  506  510  518  530
  535  541  548  555  561  563  567  577  583  586  601  603  604  607
  618  625  628  630  632  634  638  659  674  682  689  690  696  699
  700  701  703  705  707  716  717  720  727  729  741  752  757  765
  769  778  788  796  804  808  809  818  823  828  831  832  836  846
  848  865  873  876  884  890  892  893  894  895  897  910  918  925
  931  936  942  948  949  951  953  955  962  964  969  974  975  978
  980  983  995 1000 1009 1011 1016 1025 1030 1041 1043 1044 1077 1081
 1082 1084 1087 1090 1094 1102 1103 1105 1107 1114 1119 1122 1123 1125
 1126 1128 1134 1135 1139 1144 1153 1155 1162 1183 1193 1206 1208   40
   55   77  106  112  125  126  135  143  171  276  300  318  328  347
  352  396  445  461  499  517  594  600  649  669  711  791  810  816
  870  880  882  944  947  989  994  997 1006 1020 1042 1054 1117 1136
 1156 1158 1189 1191 1205    3    8    9   11   18   21   39   41   44
   46   56   58   59   60   63   65   67   73   74   81   83   90   92
   93   95  103  113  117  121  130  131  140  148  154  155  158  160
  164  175  184  193  194  199  205  206  212  213  223  226  240  241
  242  244  249  255  257  270  271  272  274  277  278  282  297  304
  313  319  325  327  331  332  334  342  344  345  349  356  359  365
  369  374  379  397  403  405  407  408  411  413  414  415  419  420
  423  425  434  437  438  443  449  466  468  472  474  480  486  489
  508  512  519  522  527  532  533  537  544  550  554  556  557  559
  568  571  576  587  602  605  609  613  624  635  636  646  662  676
  680  709  710  714  718  731  734  735  736  745  748  777  780  794
  797  798  799  802  817  826  838  840  841  851  854  856  862  872
  874  877  879  889  891  896  898  900  902  903  906  907  914  923
  924  930  939  941  943  966  967  968  971  990  992  998  999 1003
 1014 1015 1024 1029 1031 1035 1038 1048 1058 1061 1065 1072 1080 1098
 1104 1112 1116 1121 1130 1142 1143 1146 1157 1159 1160 1161 1163 1172
 1180 1187 1194 1196 1203    0  124  168  220  303  373  389  409  417
  427  473  520  569  616  623  637  648  654  655  693  694  715  774
  790  833  857  899  929  972  986  993 1018 1037 1045 1055 1111 1154
 1167 1178 1198 1204]

In [22]:
for i in models:
    print(i.support_vectors_)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]

In [37]:
X

,buying_1,buying_2,buying_3,maint_1,maint_2,maint_3,doors_1,doors_2,doors_3,persons_1,persons_2,lug_boot_1,lug_boot_2,safety_1,safety_2
1178,0,1,0,0,1,0,0,0,1,1,0,0,0,0,0
585,0,0,0,0,0,0,1,0,0,0,1,0,1,1,0
1552,1,0,0,0,1,0,1,0,0,1,0,1,0,0,1
1169,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0
1033,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,0,1,0,0,1,0,1,0,0,0,1,1,0,0,0
1294,0,1,0,1,0,0,0,0,1,0,1,0,0,0,1
860,0,0,0,1,0,0,0,0,1,0,1,1,0,0,0
1459,1,0,0,0,0,0,0,1,0,0,0,0,1,0,1
1126,0,1,0,0,1,0,1,0,0,0,1,0,1,0,1

In [38]:
import numpy as np
import matplotlib.pyplot as plt
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
h = .02  
# create a mesh to plot in
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))
# title for the plots
titles = ['SVC with linear kernel',
          'LinearSVC (linear kernel)',
          'SVC with RBF kernel',
          'SVC with polynomial (degree 3) kernel']
for i, clf in enumerate(tuple(models)):
    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    plt.subplot(2, 2, i + 1)
    plt.subplots_adjust(wspace=0.4, hspace=0.4)

    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, cmap=plt.cm.coolwarm, alpha=0.8)

    # Plot also the training points
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.coolwarm)
    plt.xlabel('Sepal length')
    plt.ylabel('Sepal width')
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.xticks(())
    plt.yticks(())
    plt.title(titles[i])

plt.show()

InvalidIndexError: (slice(None, None, None), 0)